In [2]:
from MIOFlow.models import make_model
import torch

In [3]:
batch_size = 32
feature_dim = 10
output_dim = 10

x = torch.randn(batch_size, feature_dim)
# m0 = torch.ones(batch_size, 1)
# xm = torch.cat([x, m0], dim=1)
t = torch.linspace(0, 1, 17)

model = make_model(feature_dims=feature_dim, output_dims=output_dim, which='ode_growth_rate')

In [4]:
xt, mt = model(x, t)

In [5]:
xt.shape, mt.shape

(torch.Size([32, 10]), torch.Size([32]))

In [6]:
xtseq, mtseq = model(x, t, return_whole_sequence=True)

In [7]:
xtseq.shape

torch.Size([17, 32, 10])

In [8]:
mtseq.shape

torch.Size([17, 32])

In [15]:
torch.nn.functional.softmax(mt, dim=-1) * mt.shape[-1]

tensor([1.0268, 0.9224, 1.1414, 0.9453, 0.9940, 0.8690, 0.7887, 1.4091, 0.9651,
        0.9711, 1.1128, 0.9568, 0.8868, 1.0285, 1.1425, 0.8906, 0.7197, 0.9950,
        1.0703, 1.0634, 0.9162, 0.8831, 0.9583, 1.1062, 1.0253, 1.2900, 0.8597,
        0.8743, 0.9774, 0.8879, 1.2474, 1.0749], grad_fn=<MulBackward0>)

In [10]:
torch.exp(mt)/torch.exp(mt).sum(dim=0)

tensor([0.0321, 0.0288, 0.0357, 0.0295, 0.0311, 0.0272, 0.0246, 0.0440, 0.0302,
        0.0303, 0.0348, 0.0299, 0.0277, 0.0321, 0.0357, 0.0278, 0.0225, 0.0311,
        0.0334, 0.0332, 0.0286, 0.0276, 0.0299, 0.0346, 0.0320, 0.0403, 0.0269,
        0.0273, 0.0305, 0.0277, 0.0390, 0.0336], grad_fn=<DivBackward0>)

In [16]:
torch.nn.functional.softmax(mtseq, dim=-1) * mtseq.shape[-1]

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0026, 0.9937, 1.0069, 0.9955, 1.0003, 0.9921, 0.9858, 1.0248, 0.9971,
         0.9992, 1.0086, 0.9955, 0.9940, 1.0021, 1.0077, 0.9937, 0.9788, 0.9973,
         1.0049, 1.0046, 0.9954, 0.9949, 0.9994, 1.0110, 1.0021, 1.0186, 0.9897,
         0.9929, 0.9975, 0.9936, 1.0151, 1.0045],
        [1.0051, 0.9875, 1.0141, 0.9912, 1.0005, 0.9843, 0.9715, 1.0498, 0.9941,
         0.9983, 1.0170, 0.9912, 0.9880, 1.0041, 1.0155, 0.9874, 0.9581, 0.9950,
         1.0097, 1.0091, 0.9907, 0.9895, 0.9985, 1.0213, 1.0042, 1.0372, 0.9797,
         0.9856, 0.9953, 0.9872, 1.0301, 1.0090],
        [1.0075, 0.9816, 1.0215, 0.9869, 1.0007, 0.9764, 0.9574, 1.0748, 0.9911,
         0.9973, 1.0251, 0.9872, 0.9818,

In [13]:
mtseq.shape

torch.Size([17, 32])